# Makefile.in generated by automake 1.11.3 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/dines
pkgincludedir = $(includedir)/dines
pkglibdir = $(libdir)/dines
pkglibexecdir = $(libexecdir)/dines
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = dines$(EXEEXT) test_dines$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure AUTHORS COPYING ChangeLog INSTALL NEWS \
	depcomp install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_dines_OBJECTS = dines-dns_header.$(OBJEXT) \
	dines-dns_packet.$(OBJEXT) dines-dns_question.$(OBJEXT) \
	dines-in_cksum.$(OBJEXT) dines-main.$(OBJEXT) \
	dines-rr.$(OBJEXT) dines-tokenizer.$(OBJEXT) \
	dines-convert.$(OBJEXT)
dines_OBJECTS = $(am_dines_OBJECTS)
dines_LDADD = $(LDADD)
dines_LINK = $(CXXLD) $(dines_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
am_test_dines_OBJECTS = test_dines-dns_header.$(OBJEXT) \
	test_dines-dns_packet.$(OBJEXT) \
	test_dines-dns_question.$(OBJEXT) \
	test_dines-in_cksum.$(OBJEXT) test_dines-test.$(OBJEXT) \
	test_dines-rr.$(OBJEXT) test_dines-tokenizer.$(OBJEXT) \
	test_dines-convert.$(OBJEXT)
test_dines_OBJECTS = $(am_test_dines_OBJECTS)
test_dines_LDADD = $(LDADD)
test_dines_LINK = $(CXXLD) $(test_dines_CXXFLAGS) $(CXXFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(dines_SOURCES) $(test_dines_SOURCES)
DIST_SOURCES = $(dines_SOURCES) $(test_dines_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/dario/Projects/dines/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AUTOCONF = ${SHELL} /home/dario/Projects/dines/missing --run autoconf
AUTOHEADER = ${SHELL} /home/dario/Projects/dines/missing --run autoheader
AUTOMAKE = ${SHELL} /home/dario/Projects/dines/missing --run automake-1.11
AWK = mawk
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EXEEXT = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/dario/Projects/dines/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = dines
PACKAGE_BUGREPORT = lomato@gmail.com
PACKAGE_NAME = Dines
PACKAGE_STRING = Dines 0.4
PACKAGE_TARNAME = dines
PACKAGE_URL = http://github.com/crondaemon/dines
PACKAGE_VERSION = 0.4
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 0.4
abs_builddir = /home/dario/Projects/dines
abs_srcdir = /home/dario/Projects/dines
abs_top_builddir = /home/dario/Projects/dines
abs_top_srcdir = /home/dario/Projects/dines
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/dario/Projects/dines/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
dines_SOURCES = debug.hpp dns_header.hpp dns_packet.hpp dns_question.hpp in_cksum.hpp rr.hpp tokenizer.hpp version.hpp dns_header.cpp dns_packet.cpp dns_question.cpp in_cksum.cpp main.cpp rr.cpp tokenizer.cpp convert.cpp
dines_CXXFLAGS = -Wall
test_dines_SOURCES = debug.hpp dns_header.hpp dns_packet.hpp dns_question.hpp in_cksum.hpp rr.hpp tokenizer.hpp version.hpp dns_header.cpp dns_packet.cpp dns_question.cpp in_cksum.cpp test.cpp rr.cpp tokenizer.cpp convert.cpp convert.hpp
test_dines_CXXFLAGS = -Wall
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then rm -f stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) stamp-h1; else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
dines$(EXEEXT): $(dines_OBJECTS) $(dines_DEPENDENCIES) $(EXTRA_dines_DEPENDENCIES) 
	@rm -f dines$(EXEEXT)
	$(dines_LINK) $(dines_OBJECTS) $(dines_LDADD) $(LIBS)
test_dines$(EXEEXT): $(test_dines_OBJECTS) $(test_dines_DEPENDENCIES) $(EXTRA_test_dines_DEPENDENCIES) 
	@rm -f test_dines$(EXEEXT)
	$(test_dines_LINK) $(test_dines_OBJECTS) $(test_dines_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/dines-convert.Po
include ./$(DEPDIR)/dines-dns_header.Po
include ./$(DEPDIR)/dines-dns_packet.Po
include ./$(DEPDIR)/dines-dns_question.Po
include ./$(DEPDIR)/dines-in_cksum.Po
include ./$(DEPDIR)/dines-main.Po
include ./$(DEPDIR)/dines-rr.Po
include ./$(DEPDIR)/dines-tokenizer.Po
include ./$(DEPDIR)/test_dines-convert.Po
include ./$(DEPDIR)/test_dines-dns_header.Po
include ./$(DEPDIR)/test_dines-dns_packet.Po
include ./$(DEPDIR)/test_dines-dns_question.Po
include ./$(DEPDIR)/test_dines-in_cksum.Po
include ./$(DEPDIR)/test_dines-rr.Po
include ./$(DEPDIR)/test_dines-test.Po
include ./$(DEPDIR)/test_dines-tokenizer.Po

.cpp.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

dines-dns_header.o: dns_header.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-dns_header.o -MD -MP -MF $(DEPDIR)/dines-dns_header.Tpo -c -o dines-dns_header.o `test -f 'dns_header.cpp' || echo '$(srcdir)/'`dns_header.cpp
	$(am__mv) $(DEPDIR)/dines-dns_header.Tpo $(DEPDIR)/dines-dns_header.Po
#	source='dns_header.cpp' object='dines-dns_header.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-dns_header.o `test -f 'dns_header.cpp' || echo '$(srcdir)/'`dns_header.cpp

dines-dns_header.obj: dns_header.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-dns_header.obj -MD -MP -MF $(DEPDIR)/dines-dns_header.Tpo -c -o dines-dns_header.obj `if test -f 'dns_header.cpp'; then $(CYGPATH_W) 'dns_header.cpp'; else $(CYGPATH_W) '$(srcdir)/dns_header.cpp'; fi`
	$(am__mv) $(DEPDIR)/dines-dns_header.Tpo $(DEPDIR)/dines-dns_header.Po
#	source='dns_header.cpp' object='dines-dns_header.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-dns_header.obj `if test -f 'dns_header.cpp'; then $(CYGPATH_W) 'dns_header.cpp'; else $(CYGPATH_W) '$(srcdir)/dns_header.cpp'; fi`

dines-dns_packet.o: dns_packet.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-dns_packet.o -MD -MP -MF $(DEPDIR)/dines-dns_packet.Tpo -c -o dines-dns_packet.o `test -f 'dns_packet.cpp' || echo '$(srcdir)/'`dns_packet.cpp
	$(am__mv) $(DEPDIR)/dines-dns_packet.Tpo $(DEPDIR)/dines-dns_packet.Po
#	source='dns_packet.cpp' object='dines-dns_packet.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-dns_packet.o `test -f 'dns_packet.cpp' || echo '$(srcdir)/'`dns_packet.cpp

dines-dns_packet.obj: dns_packet.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-dns_packet.obj -MD -MP -MF $(DEPDIR)/dines-dns_packet.Tpo -c -o dines-dns_packet.obj `if test -f 'dns_packet.cpp'; then $(CYGPATH_W) 'dns_packet.cpp'; else $(CYGPATH_W) '$(srcdir)/dns_packet.cpp'; fi`
	$(am__mv) $(DEPDIR)/dines-dns_packet.Tpo $(DEPDIR)/dines-dns_packet.Po
#	source='dns_packet.cpp' object='dines-dns_packet.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-dns_packet.obj `if test -f 'dns_packet.cpp'; then $(CYGPATH_W) 'dns_packet.cpp'; else $(CYGPATH_W) '$(srcdir)/dns_packet.cpp'; fi`

dines-dns_question.o: dns_question.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-dns_question.o -MD -MP -MF $(DEPDIR)/dines-dns_question.Tpo -c -o dines-dns_question.o `test -f 'dns_question.cpp' || echo '$(srcdir)/'`dns_question.cpp
	$(am__mv) $(DEPDIR)/dines-dns_question.Tpo $(DEPDIR)/dines-dns_question.Po
#	source='dns_question.cpp' object='dines-dns_question.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-dns_question.o `test -f 'dns_question.cpp' || echo '$(srcdir)/'`dns_question.cpp

dines-dns_question.obj: dns_question.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-dns_question.obj -MD -MP -MF $(DEPDIR)/dines-dns_question.Tpo -c -o dines-dns_question.obj `if test -f 'dns_question.cpp'; then $(CYGPATH_W) 'dns_question.cpp'; else $(CYGPATH_W) '$(srcdir)/dns_question.cpp'; fi`
	$(am__mv) $(DEPDIR)/dines-dns_question.Tpo $(DEPDIR)/dines-dns_question.Po
#	source='dns_question.cpp' object='dines-dns_question.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-dns_question.obj `if test -f 'dns_question.cpp'; then $(CYGPATH_W) 'dns_question.cpp'; else $(CYGPATH_W) '$(srcdir)/dns_question.cpp'; fi`

dines-in_cksum.o: in_cksum.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-in_cksum.o -MD -MP -MF $(DEPDIR)/dines-in_cksum.Tpo -c -o dines-in_cksum.o `test -f 'in_cksum.cpp' || echo '$(srcdir)/'`in_cksum.cpp
	$(am__mv) $(DEPDIR)/dines-in_cksum.Tpo $(DEPDIR)/dines-in_cksum.Po
#	source='in_cksum.cpp' object='dines-in_cksum.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-in_cksum.o `test -f 'in_cksum.cpp' || echo '$(srcdir)/'`in_cksum.cpp

dines-in_cksum.obj: in_cksum.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-in_cksum.obj -MD -MP -MF $(DEPDIR)/dines-in_cksum.Tpo -c -o dines-in_cksum.obj `if test -f 'in_cksum.cpp'; then $(CYGPATH_W) 'in_cksum.cpp'; else $(CYGPATH_W) '$(srcdir)/in_cksum.cpp'; fi`
	$(am__mv) $(DEPDIR)/dines-in_cksum.Tpo $(DEPDIR)/dines-in_cksum.Po
#	source='in_cksum.cpp' object='dines-in_cksum.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-in_cksum.obj `if test -f 'in_cksum.cpp'; then $(CYGPATH_W) 'in_cksum.cpp'; else $(CYGPATH_W) '$(srcdir)/in_cksum.cpp'; fi`

dines-main.o: main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-main.o -MD -MP -MF $(DEPDIR)/dines-main.Tpo -c -o dines-main.o `test -f 'main.cpp' || echo '$(srcdir)/'`main.cpp
	$(am__mv) $(DEPDIR)/dines-main.Tpo $(DEPDIR)/dines-main.Po
#	source='main.cpp' object='dines-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-main.o `test -f 'main.cpp' || echo '$(srcdir)/'`main.cpp

dines-main.obj: main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-main.obj -MD -MP -MF $(DEPDIR)/dines-main.Tpo -c -o dines-main.obj `if test -f 'main.cpp'; then $(CYGPATH_W) 'main.cpp'; else $(CYGPATH_W) '$(srcdir)/main.cpp'; fi`
	$(am__mv) $(DEPDIR)/dines-main.Tpo $(DEPDIR)/dines-main.Po
#	source='main.cpp' object='dines-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-main.obj `if test -f 'main.cpp'; then $(CYGPATH_W) 'main.cpp'; else $(CYGPATH_W) '$(srcdir)/main.cpp'; fi`

dines-rr.o: rr.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-rr.o -MD -MP -MF $(DEPDIR)/dines-rr.Tpo -c -o dines-rr.o `test -f 'rr.cpp' || echo '$(srcdir)/'`rr.cpp
	$(am__mv) $(DEPDIR)/dines-rr.Tpo $(DEPDIR)/dines-rr.Po
#	source='rr.cpp' object='dines-rr.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-rr.o `test -f 'rr.cpp' || echo '$(srcdir)/'`rr.cpp

dines-rr.obj: rr.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-rr.obj -MD -MP -MF $(DEPDIR)/dines-rr.Tpo -c -o dines-rr.obj `if test -f 'rr.cpp'; then $(CYGPATH_W) 'rr.cpp'; else $(CYGPATH_W) '$(srcdir)/rr.cpp'; fi`
	$(am__mv) $(DEPDIR)/dines-rr.Tpo $(DEPDIR)/dines-rr.Po
#	source='rr.cpp' object='dines-rr.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-rr.obj `if test -f 'rr.cpp'; then $(CYGPATH_W) 'rr.cpp'; else $(CYGPATH_W) '$(srcdir)/rr.cpp'; fi`

dines-tokenizer.o: tokenizer.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-tokenizer.o -MD -MP -MF $(DEPDIR)/dines-tokenizer.Tpo -c -o dines-tokenizer.o `test -f 'tokenizer.cpp' || echo '$(srcdir)/'`tokenizer.cpp
	$(am__mv) $(DEPDIR)/dines-tokenizer.Tpo $(DEPDIR)/dines-tokenizer.Po
#	source='tokenizer.cpp' object='dines-tokenizer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-tokenizer.o `test -f 'tokenizer.cpp' || echo '$(srcdir)/'`tokenizer.cpp

dines-tokenizer.obj: tokenizer.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-tokenizer.obj -MD -MP -MF $(DEPDIR)/dines-tokenizer.Tpo -c -o dines-tokenizer.obj `if test -f 'tokenizer.cpp'; then $(CYGPATH_W) 'tokenizer.cpp'; else $(CYGPATH_W) '$(srcdir)/tokenizer.cpp'; fi`
	$(am__mv) $(DEPDIR)/dines-tokenizer.Tpo $(DEPDIR)/dines-tokenizer.Po
#	source='tokenizer.cpp' object='dines-tokenizer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-tokenizer.obj `if test -f 'tokenizer.cpp'; then $(CYGPATH_W) 'tokenizer.cpp'; else $(CYGPATH_W) '$(srcdir)/tokenizer.cpp'; fi`

dines-convert.o: convert.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-convert.o -MD -MP -MF $(DEPDIR)/dines-convert.Tpo -c -o dines-convert.o `test -f 'convert.cpp' || echo '$(srcdir)/'`convert.cpp
	$(am__mv) $(DEPDIR)/dines-convert.Tpo $(DEPDIR)/dines-convert.Po
#	source='convert.cpp' object='dines-convert.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-convert.o `test -f 'convert.cpp' || echo '$(srcdir)/'`convert.cpp

dines-convert.obj: convert.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -MT dines-convert.obj -MD -MP -MF $(DEPDIR)/dines-convert.Tpo -c -o dines-convert.obj `if test -f 'convert.cpp'; then $(CYGPATH_W) 'convert.cpp'; else $(CYGPATH_W) '$(srcdir)/convert.cpp'; fi`
	$(am__mv) $(DEPDIR)/dines-convert.Tpo $(DEPDIR)/dines-convert.Po
#	source='convert.cpp' object='dines-convert.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dines_CXXFLAGS) $(CXXFLAGS) -c -o dines-convert.obj `if test -f 'convert.cpp'; then $(CYGPATH_W) 'convert.cpp'; else $(CYGPATH_W) '$(srcdir)/convert.cpp'; fi`

test_dines-dns_header.o: dns_header.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-dns_header.o -MD -MP -MF $(DEPDIR)/test_dines-dns_header.Tpo -c -o test_dines-dns_header.o `test -f 'dns_header.cpp' || echo '$(srcdir)/'`dns_header.cpp
	$(am__mv) $(DEPDIR)/test_dines-dns_header.Tpo $(DEPDIR)/test_dines-dns_header.Po
#	source='dns_header.cpp' object='test_dines-dns_header.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-dns_header.o `test -f 'dns_header.cpp' || echo '$(srcdir)/'`dns_header.cpp

test_dines-dns_header.obj: dns_header.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-dns_header.obj -MD -MP -MF $(DEPDIR)/test_dines-dns_header.Tpo -c -o test_dines-dns_header.obj `if test -f 'dns_header.cpp'; then $(CYGPATH_W) 'dns_header.cpp'; else $(CYGPATH_W) '$(srcdir)/dns_header.cpp'; fi`
	$(am__mv) $(DEPDIR)/test_dines-dns_header.Tpo $(DEPDIR)/test_dines-dns_header.Po
#	source='dns_header.cpp' object='test_dines-dns_header.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-dns_header.obj `if test -f 'dns_header.cpp'; then $(CYGPATH_W) 'dns_header.cpp'; else $(CYGPATH_W) '$(srcdir)/dns_header.cpp'; fi`

test_dines-dns_packet.o: dns_packet.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-dns_packet.o -MD -MP -MF $(DEPDIR)/test_dines-dns_packet.Tpo -c -o test_dines-dns_packet.o `test -f 'dns_packet.cpp' || echo '$(srcdir)/'`dns_packet.cpp
	$(am__mv) $(DEPDIR)/test_dines-dns_packet.Tpo $(DEPDIR)/test_dines-dns_packet.Po
#	source='dns_packet.cpp' object='test_dines-dns_packet.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-dns_packet.o `test -f 'dns_packet.cpp' || echo '$(srcdir)/'`dns_packet.cpp

test_dines-dns_packet.obj: dns_packet.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-dns_packet.obj -MD -MP -MF $(DEPDIR)/test_dines-dns_packet.Tpo -c -o test_dines-dns_packet.obj `if test -f 'dns_packet.cpp'; then $(CYGPATH_W) 'dns_packet.cpp'; else $(CYGPATH_W) '$(srcdir)/dns_packet.cpp'; fi`
	$(am__mv) $(DEPDIR)/test_dines-dns_packet.Tpo $(DEPDIR)/test_dines-dns_packet.Po
#	source='dns_packet.cpp' object='test_dines-dns_packet.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-dns_packet.obj `if test -f 'dns_packet.cpp'; then $(CYGPATH_W) 'dns_packet.cpp'; else $(CYGPATH_W) '$(srcdir)/dns_packet.cpp'; fi`

test_dines-dns_question.o: dns_question.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-dns_question.o -MD -MP -MF $(DEPDIR)/test_dines-dns_question.Tpo -c -o test_dines-dns_question.o `test -f 'dns_question.cpp' || echo '$(srcdir)/'`dns_question.cpp
	$(am__mv) $(DEPDIR)/test_dines-dns_question.Tpo $(DEPDIR)/test_dines-dns_question.Po
#	source='dns_question.cpp' object='test_dines-dns_question.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-dns_question.o `test -f 'dns_question.cpp' || echo '$(srcdir)/'`dns_question.cpp

test_dines-dns_question.obj: dns_question.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-dns_question.obj -MD -MP -MF $(DEPDIR)/test_dines-dns_question.Tpo -c -o test_dines-dns_question.obj `if test -f 'dns_question.cpp'; then $(CYGPATH_W) 'dns_question.cpp'; else $(CYGPATH_W) '$(srcdir)/dns_question.cpp'; fi`
	$(am__mv) $(DEPDIR)/test_dines-dns_question.Tpo $(DEPDIR)/test_dines-dns_question.Po
#	source='dns_question.cpp' object='test_dines-dns_question.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-dns_question.obj `if test -f 'dns_question.cpp'; then $(CYGPATH_W) 'dns_question.cpp'; else $(CYGPATH_W) '$(srcdir)/dns_question.cpp'; fi`

test_dines-in_cksum.o: in_cksum.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-in_cksum.o -MD -MP -MF $(DEPDIR)/test_dines-in_cksum.Tpo -c -o test_dines-in_cksum.o `test -f 'in_cksum.cpp' || echo '$(srcdir)/'`in_cksum.cpp
	$(am__mv) $(DEPDIR)/test_dines-in_cksum.Tpo $(DEPDIR)/test_dines-in_cksum.Po
#	source='in_cksum.cpp' object='test_dines-in_cksum.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-in_cksum.o `test -f 'in_cksum.cpp' || echo '$(srcdir)/'`in_cksum.cpp

test_dines-in_cksum.obj: in_cksum.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-in_cksum.obj -MD -MP -MF $(DEPDIR)/test_dines-in_cksum.Tpo -c -o test_dines-in_cksum.obj `if test -f 'in_cksum.cpp'; then $(CYGPATH_W) 'in_cksum.cpp'; else $(CYGPATH_W) '$(srcdir)/in_cksum.cpp'; fi`
	$(am__mv) $(DEPDIR)/test_dines-in_cksum.Tpo $(DEPDIR)/test_dines-in_cksum.Po
#	source='in_cksum.cpp' object='test_dines-in_cksum.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-in_cksum.obj `if test -f 'in_cksum.cpp'; then $(CYGPATH_W) 'in_cksum.cpp'; else $(CYGPATH_W) '$(srcdir)/in_cksum.cpp'; fi`

test_dines-test.o: test.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-test.o -MD -MP -MF $(DEPDIR)/test_dines-test.Tpo -c -o test_dines-test.o `test -f 'test.cpp' || echo '$(srcdir)/'`test.cpp
	$(am__mv) $(DEPDIR)/test_dines-test.Tpo $(DEPDIR)/test_dines-test.Po
#	source='test.cpp' object='test_dines-test.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-test.o `test -f 'test.cpp' || echo '$(srcdir)/'`test.cpp

test_dines-test.obj: test.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-test.obj -MD -MP -MF $(DEPDIR)/test_dines-test.Tpo -c -o test_dines-test.obj `if test -f 'test.cpp'; then $(CYGPATH_W) 'test.cpp'; else $(CYGPATH_W) '$(srcdir)/test.cpp'; fi`
	$(am__mv) $(DEPDIR)/test_dines-test.Tpo $(DEPDIR)/test_dines-test.Po
#	source='test.cpp' object='test_dines-test.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-test.obj `if test -f 'test.cpp'; then $(CYGPATH_W) 'test.cpp'; else $(CYGPATH_W) '$(srcdir)/test.cpp'; fi`

test_dines-rr.o: rr.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-rr.o -MD -MP -MF $(DEPDIR)/test_dines-rr.Tpo -c -o test_dines-rr.o `test -f 'rr.cpp' || echo '$(srcdir)/'`rr.cpp
	$(am__mv) $(DEPDIR)/test_dines-rr.Tpo $(DEPDIR)/test_dines-rr.Po
#	source='rr.cpp' object='test_dines-rr.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-rr.o `test -f 'rr.cpp' || echo '$(srcdir)/'`rr.cpp

test_dines-rr.obj: rr.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-rr.obj -MD -MP -MF $(DEPDIR)/test_dines-rr.Tpo -c -o test_dines-rr.obj `if test -f 'rr.cpp'; then $(CYGPATH_W) 'rr.cpp'; else $(CYGPATH_W) '$(srcdir)/rr.cpp'; fi`
	$(am__mv) $(DEPDIR)/test_dines-rr.Tpo $(DEPDIR)/test_dines-rr.Po
#	source='rr.cpp' object='test_dines-rr.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-rr.obj `if test -f 'rr.cpp'; then $(CYGPATH_W) 'rr.cpp'; else $(CYGPATH_W) '$(srcdir)/rr.cpp'; fi`

test_dines-tokenizer.o: tokenizer.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-tokenizer.o -MD -MP -MF $(DEPDIR)/test_dines-tokenizer.Tpo -c -o test_dines-tokenizer.o `test -f 'tokenizer.cpp' || echo '$(srcdir)/'`tokenizer.cpp
	$(am__mv) $(DEPDIR)/test_dines-tokenizer.Tpo $(DEPDIR)/test_dines-tokenizer.Po
#	source='tokenizer.cpp' object='test_dines-tokenizer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-tokenizer.o `test -f 'tokenizer.cpp' || echo '$(srcdir)/'`tokenizer.cpp

test_dines-tokenizer.obj: tokenizer.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-tokenizer.obj -MD -MP -MF $(DEPDIR)/test_dines-tokenizer.Tpo -c -o test_dines-tokenizer.obj `if test -f 'tokenizer.cpp'; then $(CYGPATH_W) 'tokenizer.cpp'; else $(CYGPATH_W) '$(srcdir)/tokenizer.cpp'; fi`
	$(am__mv) $(DEPDIR)/test_dines-tokenizer.Tpo $(DEPDIR)/test_dines-tokenizer.Po
#	source='tokenizer.cpp' object='test_dines-tokenizer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-tokenizer.obj `if test -f 'tokenizer.cpp'; then $(CYGPATH_W) 'tokenizer.cpp'; else $(CYGPATH_W) '$(srcdir)/tokenizer.cpp'; fi`

test_dines-convert.o: convert.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-convert.o -MD -MP -MF $(DEPDIR)/test_dines-convert.Tpo -c -o test_dines-convert.o `test -f 'convert.cpp' || echo '$(srcdir)/'`convert.cpp
	$(am__mv) $(DEPDIR)/test_dines-convert.Tpo $(DEPDIR)/test_dines-convert.Po
#	source='convert.cpp' object='test_dines-convert.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-convert.o `test -f 'convert.cpp' || echo '$(srcdir)/'`convert.cpp

test_dines-convert.obj: convert.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -MT test_dines-convert.obj -MD -MP -MF $(DEPDIR)/test_dines-convert.Tpo -c -o test_dines-convert.obj `if test -f 'convert.cpp'; then $(CYGPATH_W) 'convert.cpp'; else $(CYGPATH_W) '$(srcdir)/convert.cpp'; fi`
	$(am__mv) $(DEPDIR)/test_dines-convert.Tpo $(DEPDIR)/test_dines-convert.Po
#	source='convert.cpp' object='test_dines-convert.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(test_dines_CXXFLAGS) $(CXXFLAGS) -c -o test_dines-convert.obj `if test -f 'convert.cpp'; then $(CYGPATH_W) 'convert.cpp'; else $(CYGPATH_W) '$(srcdir)/convert.cpp'; fi`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-lzma dist-shar dist-tarZ dist-xz \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS

test: test_dines
	./test_dines

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
